### ISSUE TITLE
Move new fishing system and water and lava catch to an own mod

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Extended#104]
https://github.com/NightKosh/Advanced-Fishing

TODO :
- [x] loot tables
- [x] Enchanted skull catch in lava

**Comment by coldblacksnow** [comment]
оставь удочку в екстендед, мне она нравится D:

**Comment by NightKosh** [comment]
Удочку и энчант убирать не буду. Изначально хотел лишь рыбачить в лаве, а в итоге потребовалось чуть ли не всё переделывать, что уже тянет на полноценный мод.
