### ISSUE TITLE
huge fps lag because of too many mobs spawning

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Extended#106]
https://github.com/NightKosh/Gravestone-mod-Graves/issues/251

> Hi i'm getting huge fps lag from the sheer amount of mobs spawning in the water (divers, drowned etc) its making the game unplayable. im using the latest version of the extended mod. GraveStone-Extended-1.3.0a3. theres literally like 100+ mobs spawning at once

**Comment by NightKosh** [comment]
@mattrix444 I reduced their spawn rate & amount. Not sure will it be enough. Try the latest version and give me feedback please. (I'll post a link on new version when it will be available - it is under review at curse forge)

**Comment by NightKosh** [comment]
@mattrix444 here is a new version https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2522256

**Comment by P3rf3ctXZer0** [comment]
Crash with newest version "ServerSide" Check log for details and specs
https://gist.github.com/P3rf3ctXZer0/87bcf421bbc6b69a37520647c0095a76

**Comment by NightKosh** [comment]
@P3rf3ctXZer0 fixed - https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2522338

**Comment by NightKosh** [comment]
Ok I reduced its spawn weight again, and added an option, to make it configurable - "PhantomDiverSpawnWeight"

**Comment by NightKosh** [comment]
Could someone post here a screenshot? There weren't huge amount of them while testing.

**Comment by NightKosh** [comment]
Also, there are an options(in latest version) to completelly disable some mobs

**Comment by P3rf3ctXZer0** [comment]
Oh sorry been busy I noticed the config so I toned spawns down. It was mostly the drowned zombies that seemed to overflow.

**Comment by NightKosh** [comment]
@P3rf3ctXZer0 Could you please provide me a full list of mods you are using?

**Comment by P3rf3ctXZer0** [comment]
Oh sorry I have long since removed your mod I am sorry. At some point in 1.13 I may re-add it but for now my mod-pack is pretty perfect.
