### ISSUE TITLE
Crash when trying to get harvest speed of chisel

### ISSUE THREAD

**Issue by SilentChaos512** [NightKosh/Gravestone-mod-Extended#108]
My mod, Silent's Gems, adds some additional tooltips to other items like tools, displaying things like harvest speed. A user reported a crash involving your chisel item. Seems to be because the chisel's effectiveBlocks set is null. It should be an empty set instead.

Original issue: https://github.com/SilentChaos512/SilentGems/issues/278
Replicated crash: https://gist.github.com/SilentChaos512/1f73ffd500308f5f7783e2177193704e

**Comment by NightKosh** [comment]
Fixed version https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2522256
