### ISSUE TITLE
Bug/FYI - Swamp Thing mob saturation

### ISSUE THREAD

**Issue by Nexusdog** [NightKosh/Gravestone-mod-Extended#116]
MC/F 1.12.2/2611

I just found a swamp full of Swamp Things, hundreds of the bloody things, in a Wetlands biome. Set config to false but just a heads up for this bug.

**Comment by NightKosh** [comment]
Hello. Thank you for report. 
Could you please provide more information about it? I've got few similar reports about drowned and divers ( #106 ), but unfortunately I don't know how to reproduce it - I waited a lot, but there weren't to much of them.
Are you playing alone or on server?
Also it will ne nice to get a screenshot, if it's possible.

**Comment by Nexusdog** [comment]
Ah, apologies.

Single player, heavily modded (sorry, adds to your headache I know). Interestingly, even though I set config to false, reloading the world they were still there. 

I killed them all, but I'll head out to that area again for another look & grab a screenie for you.

**Comment by NightKosh** [comment]
> Interestingly, even though I set config to false, reloading the world they were still there.

This option only disable natural spawning of this mobs.

**Comment by Nexusdog** [comment]
What criteria do they need to spawn? Biome, depth of water, block type (i.e. mud?) and so on?

I found the biome area again and no spawning now although I did replace the mud with gravel. Now off exploring the world to see if I can find another wetlands biome & whether they show up again.

**Comment by NightKosh** [comment]
It can be spawned only in swamp biomes in water in the darkness.

**Comment by NightKosh** [comment]
Could you please provide me a full list of mods you are using?
