### ISSUE TITLE
[CrashNotDesktop] When using Chunk-Pregen, Forestry

### ISSUE THREAD

**Issue by drakray** [NightKosh/Gravestone-mod-Extended#117]
https://pastebin.com/REevZxvC
MC 1.12.2
Forge 2615
Gravestone-Extended 1.3.0b3
Crashed when using /pregen startradius 0 0 64 0 PostProcessing, near 16000/16384
Crash without closing MC, create crashlog in background, must kill process to continue

**Comment by NightKosh** [comment]
Try new version please https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2530743

**Comment by NightKosh** [comment]
Did you tried it?

**Comment by drakray** [comment]
I did, I haven't got crash yet, but I didn't do extensive test either.
I'l try something big and keep you posted :)

**Comment by drakray** [comment]
Tried a Pregen of 65536 chunk, no crash \o/
Could just be luck though, but still :P
