### ISSUE TITLE
[REQUEST] Better configs for dealing with mob spawns

### ISSUE THREAD

**Issue by Sunconure11** [NightKosh/Gravestone-mod-Extended#125]
A player in my pack is having some issues with massive, runaway spawns, from swamp things, with this mod installed into it. This mod needs some better configs that allow me to configure the spawn rates and numbers of mobs that spawn from it. The resultant lag the mobs can cause is insane.

Note: The issue is happening in a modded biome, from Biomes O' Plenty.

**Comment by NightKosh** [comment]
Hello.
I already got few similar issues: #116 #106 . But, unfortunatelly I can't reproduce those problem and this issues doesn't provide anyfing usefull.

Thank you for additional information. Hope it'll helps me.

**Comment by NightKosh** [comment]
Maybe you can provide additional information? Unfortunately I still can't reproduce it, even with Biomes O Plenty.

Vanilla world(ocean):
![2018-02-16 14 10 35](https://user-images.githubusercontent.com/4181327/36938677-20e3ae9a-1f36-11e8-9ef8-136a2fee7d59.png)

Biomes O Plenty world:

![2018-03-03 22 34 12](https://user-images.githubusercontent.com/4181327/36938695-6e835a6a-1f36-11e8-816a-7a78d0dc006e.png)
![2018-03-03 22 40 40](https://user-images.githubusercontent.com/4181327/36938696-6ea23476-1f36-11e8-8874-574ccddc973e.png)
![2018-03-03 22 44 39](https://user-images.githubusercontent.com/4181327/36938697-6ebf331e-1f36-11e8-9c66-c4ffbcc90aeb.png)
![2018-03-03 22 45 40](https://user-images.githubusercontent.com/4181327/36938698-6eddd0b2-1f36-11e8-968b-4c9d04bced91.png)

**Comment by Sunconure11** [comment]
I can send over my current config, although it has been edited in preparation for another update to my pack.


https://pastebin.com/1WVwSteU

As for pics, I've got one.

![](https://cdn.discordapp.com/attachments/407858842995785728/419577036709822465/2018-03-03_11.28.27.png)

I also do have some mods that affect difficulty. Scaling Health + Zombie Awareness, both of which can alter spawn rates.

**Comment by NightKosh** [comment]
/effect @e[type=gravestone-extended:GSSwampThing,r=?] minecraft:glowing 60000

Without mods:
![2018-03-04 13 43 46](https://user-images.githubusercontent.com/4181327/36944659-2f7bd992-1fb2-11e8-9164-6ec9bf434361.png)

 Zombie Awareness:
![2018-03-04 13 33 44](https://user-images.githubusercontent.com/4181327/36944667-3af495a2-1fb2-11e8-8731-74a2b1e0af14.png)

Scaling Health:
![2018-03-04 13 48 28](https://user-images.githubusercontent.com/4181327/36944705-c81601aa-1fb2-11e8-98a0-786e198c3ebf.png)

Scaling Health + Zombie Awareness:
![2018-03-04 13 25 54](https://user-images.githubusercontent.com/4181327/36944686-6ea70de4-1fb2-11e8-8dfa-4ff796dd775a.png)

**Comment by AdaraChristine** [comment]
I've got a lot of phantom divers in the twilight forest dim. So many that it makes it totally lag out. Im not sure if its being caused by other mods. My pack is Mystical Village 2 and world gens with OTG....not sure if that info helps. A dimension white/black list would be awesome tho! 
![lagtwilight](https://user-images.githubusercontent.com/30163566/37135371-e8c4b706-2251-11e8-89f9-37a2c006d40c.jpg)
Sorry that's all i got before crash. Removing gravestone extended fixed it but i dont want to remove your mod from my pack because i like it. :(

**Comment by NightKosh** [comment]
@AdaraChristine yes, it is already done in #113

**Comment by NightKosh** [comment]
I decided to manually check amount of mobs of the same type in the chunk to reduce its spawn. It should fix this problem.

![2018-03-08 12 01 42](https://user-images.githubusercontent.com/4181327/37142219-8353f040-22c8-11e8-9019-8ba61db20032.png)

**Comment by NightKosh** [comment]
@Sunconure11  unfortunately the options you are asking about are useless. As for example spawn rate of Divers is almost minimal and only 1 of them can be spawned. It looks like some kind of compatibility problem(or something else) so such types of configuration doesn't help. 
I hope the fix, which was described in previous post, helps.

**Comment by NightKosh** [comment]
@Sunconure11   @Nexusdog @mattrix444 @AdaraChristine  try new version please:
https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2538743

**Comment by AdaraChristine** [comment]
Solved my problems.The dimension whitelist worked
 Thanks!

**Comment by NightKosh** [comment]
Nice.

@Sunconure11 @Nexusdog @mattrix444 what about your problem? Does any additional fixes required?

**Comment by Sunconure11** [comment]
The issue has not persisted since.
