### ISSUE TITLE
User of my pack encountered a strange crash with this mod

### ISSUE THREAD

**Issue by Sunconure11** [NightKosh/Gravestone-mod-Extended#126]
https://pastebin.com/6bUr4GdA

**Comment by NightKosh** [comment]
Hello. Thank you for report. I moved it to https://github.com/NightKosh/Gravestone-mod-Graves/issues/255 cause this bug belongs to "Graves" mod. 
As said in log file grave metadata was setted to unexceptable value - it used to store direction in which graves should be rotated. I have no idea how it can happens - may be some kind of compatibility problem. 
I'll released fixed version in a few days.

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/gravestone-mod-graves/files/2540033
