### ISSUE TITLE
Gravestone placement rotated 90 degrees

### ISSUE THREAD

**Issue by Nexusdog** [NightKosh/Gravestone-mod-Extended#130]
MC/F 1.12.2/2624

Latest build (b6) 

Tested against previous version & it works fine - something went wonky with b6, I'm afraid.

**UPDATE**

Well, it seems b6 doesn't play nicely with GraveStone-1.12-Graves-1.0.14, on the face of it. I've messed around several times, swapping between different versions and so far that's what I've found.

**Comment by NightKosh** [comment]
https://github.com/NightKosh/Gravestone-mod-Extended/issues/130
