### ISSUE TITLE
Cascading WorldGen?

### ISSUE THREAD

**Issue by Nexusdog** [NightKosh/Gravestone-mod-Extended#131]
MC/F/GE 1.12.2/2654/b6

This showed up in my log file, is it pertinent or useful?

[Server thread/WARN] [FML]: Gravestone mod - Extended loaded a new chunk (32, -56  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker.

**Comment by NightKosh** [comment]
Do you know how can it be reproduced?

**Comment by Nexusdog** [comment]
Um, well it's a bit of a long story, but I started getting lag spikes in game every 30 seconds or so since around March 20th which got so bad as to make the game unplayable. I've been ripping out mods, Java & MC, doing fresh installs & rolling back my gfx card drivers ever since trying to cure it & last night finally found out about ghost chunk loading. I took a look at the log this morning to see if there were any mods left which were causing cascading worldgen and the ones showing up were GE, Ore Shrubs & Recurrent Complex (which was the worse out of the three by far).

I'm still getting the lag, but after hacking out about half the mods I had installed and with the remainders tweaking configs which impact on world gen. Still testing, still tweaking, still getting the lag but it's a Pyrrhic victory.

From what I can guess at, something changed fundamentally to cause a cumulative effect & significantly shit on MC where once the mods more or less played nicely together. 

Um, you asked for my mod list before - please accept my apologies, I didn't see your post... my bad. This is todays modlist, as yet untested with all the chunk related additions - https://www.modlister.com/user/nexusdog

If I can provide any information or be of any help, let me know.

**Comment by NightKosh** [comment]
Hello.
Sorry for silence. I was a little busy last month.

Is this problem still actual for you?
Which version of "Extended" mod did you used? Was is 1.3.0b5 ?
