### ISSUE TITLE
[SUGGESTION] Enchantment config

### ISSUE THREAD

**Issue by zEpiixz** [NightKosh/Gravestone-mod-Extended#145]
Hello,

Would be great if there could be a config for the enchantment. 
Like change the damage of Shadow of Death and so on.
Thanks!

**Comment by NightKosh** [comment]
Could you please provide me more details what kind of options you would like to have?

**Comment by zEpiixz** [comment]
Options to disable enchantments. Or even change the attack damage or so on. 
Would help modpack creators.

And side note: Maybe a config to set dim. spawns for your mobs. Because your wolfes spawn in Twillight Forest and so.
