### ISSUE TITLE
[Compat] Move entity registry to preInit

### ISSUE THREAD

**Issue by drakray** [NightKosh/Gravestone-mod-Extended#148]
Could it be possible to move GSEntity.registration(); to preInit please, that would allow CraftTweaker to be able to "see" entity for their command like .addDrop()

Thanks :)

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2608802

**Comment by drakray** [comment]
Work perfectly with CT/MT .addDrop() and .setAspects(), thanks! :D
