### ISSUE TITLE
Server crash on loading, TileEntityGraveStone cannot be cast to TileEntityMemorial

### ISSUE THREAD

**Issue by Dooglesmile** [NightKosh/Gravestone-mod-Extended#150]
Hi, I'm getting a server crash on startup with this error:
java.lang.ClassCastException: nightkosh.gravestone.tileentity.TileEntityGraveStone cannot be cast to nightkosh.gravestone_extended.tileentity.TileEntityMemorial

[crash log](https://gist.github.com/Dooglesmile/d73ebd62ea1f6337e24cacd8b90ec706)

Using Minecraft_server 1.12.2
Forge 14.23.4.2705
Graves 1.0.16
Extended 1.3.0b7

[Latest log file](https://gist.github.com/Dooglesmile/e31c94823f32efcfa3932dc640b6e37e)

Overall I'm loving these mods, I hope this is an easy enough thing to fix as I'm wanting to get back into raiding some catacombs :)

Edit:
After restoring a backup, this particular crash hasn't yet reoccurred. However I did have a couple of client crashes to desktop upon breaking my grave after dying.
I don't know what made me try it, but I removed the Infernal Mobs mod and since then I've not had any crashes with regards to the gravestones. Maybe there's something between the two mods that cause instability? It could always just be pure coincidence though.

Edit 2 30/07/2018:
Just had the same server crash again with the gravestone cannot be cast to memorial.
This is using the same versions of the mods as above.

[crash log](https://gist.github.com/Dooglesmile/d3e561927905aebdc51275093cde49ca)

**Comment by NightKosh** [comment]
Hello.
I made a fix which should prevent game crash, but unfortunately I can't understand why it happened, so it will not completelly solve your problem(only game crash).

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2608802
