### ISSUE TITLE
Rework some items renderring

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Extended#152]
- [x] Memorials
- [x]  Corpses
- [x] Gibbet
- [x] Candle
- [x] Skull Candles
- [x] Spawners
- [x] Piles of bones

TODO:
- [x] Memorials in creative tab are invisible
- [x] Some zombie villagers has no texture
- [x] Remove corpse TE
- [ ] Merge skull & candle models in Skullcandle model for spawners 
- [x] Skull candle light

**Comment by drakray** [comment]
Will the new Rendering be used for -Graves as well?

**Comment by NightKosh** [comment]
This changes doesn't affect graves rendering. It will be done later.

**Comment by drakray** [comment]
Ok thanks, that was my badly formulated question lol XD
