### ISSUE TITLE
[Crash - Ticking Entity] Happens when Catacombs are generating with the FoamFix mod loaded

### ISSUE THREAD

**Issue by Dragnier** [NightKosh/Gravestone-mod-Extended#156]
Minecraft 1.12.2
Graves - 1.3.0b8
Extended - 1.0.18
FoamFix - 0.10.1-1.12.2

[Crashlog](https://paste.dimdev.org/qopixivubi.mccrash)

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2610496
