### ISSUE TITLE
Crash with World Tooltips and/or Primitive Mobs (?)

### ISSUE THREAD

**Issue by Neglevin** [NightKosh/Gravestone-mod-Extended#159]
MC Version: 1.12.2
Forge version: 14.23.4.2670
Graves: 1.0.18
Extended: 1.2.6
World Tooltips: 1.2.7-102
Crash Report: https://paste.dimdev.org/gacesadujo.mccrash

I got this crash when I tried to break a villager grave with World Tooltips installed. The grave belonged to a Travelling Merchant from the Primitive Mobs before I disabled the mod in my pack. Maybe that could have contributed to it as well?

**Comment by NightKosh** [comment]
You said that you used Extended: 1.3.0b10 but as said in the crash log 1.2.6 version was used. Is this crash log actual?

**Comment by Neglevin** [comment]
Oh shoot my bad, it looks like I said the wrong version in my issue cause I was using another person's issue to see how to format my issue.

Edit: Okay yeah, it looks like the issue was that my version was outdated. Thanks for pointing it out to me!
