### ISSUE TITLE
Possible corpse render issue

### ISSUE THREAD

**Issue by Sunconure11** [NightKosh/Gravestone-mod-Extended#160]
https://paste.dimdev.org/dekicarihu.mccrash

User encountered this in my modpack, unsure as to what circumstances it fired

**Comment by NightKosh** [comment]
https://github.com/NightKosh/Gravestone-mod-Extended/issues/158

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2617789
