### ISSUE TITLE
can't see the icon of the item

### ISSUE THREAD

**Issue by MokoBlack** [NightKosh/Gravestone-mod-Extended#165]
Wen i open the inventory the icon of some item in this mod are blank  
but if its placeable,  i can see it normaly wen it placed

**Comment by NightKosh** [comment]
It looks like the reason of this problem somewhere in optifine. Furthermore it said on its bugtracker that this problem already fixed on latest version. Try it please

**Comment by MokoBlack** [comment]
ops by the way the same poblem with ur other mod--gravelstone graves


------------------ 原始邮件 ------------------
发件人: "Reshetnikov Dmitriy"<notifications@github.com>;
发送时间: 2018年10月12日(星期五) 下午5:30
收件人: "NightKosh/Gravestone-mod-Extended"<Gravestone-mod-Extended@noreply.github.com>;
抄送: "龙纛"<516151442@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NightKosh/Gravestone-mod-Extended] can't see the icon of theitem (#165)




It looks like the reason of this problem somewhere in optifine. Furthermore it said on its bugtracker that this problem already fixed on latest version. Try it please
