### ISSUE TITLE
GraveStone-1.12.2-Extended-1.3.0 is requiring your advanced fishing mod

### ISSUE THREAD

**Issue by darchitectlp** [NightKosh/Gravestone-mod-Extended#169]
GraveStone-1.12.2-Extended-1.3.0 is requiring your advanced fishing mod as dependency.

Thanks!

**Comment by NightKosh** [comment]
Yes, I know) Is it a problem for you?

**Comment by DEX47** [comment]
Yes.

**Comment by ArielFaye** [comment]
I don't understand the need to make the fishing mod a requirement. It would be better to leave them separate. We definitely didn't want to make fishing more complex in our world just to maintain the extended graves. I like variety, but fishing, meh. That is what fishing traps or golems etc.

**Comment by NightKosh** [comment]
@ArielFaye Originaly it was developed as a part of "Extended" mod when I worked on "Bone fishing pole". So it is needed for it, and as a source of a few ingredients for potions and crafting recipes and as alternative way to get skulls and enchanted skulls(fishing in lava and in toxic water).  In case you do not want to change fishing or would like to use other fishing mod you can set "OverrideVanillaFishing" to use minecraft fishing mechanic (except at fishing with "Blazing fishing pole" or "Bone fishing pole")

**Comment by nickjackson-ff** [comment]
I want GS-Extended, but not the dozens of fish, recipes, and things that Advanced Fishing adds. It would be nice to at least have an option to disable registration of the additional content.

**Comment by estradus** [comment]
Like, instead of a hard requirement, perhaps you could have it so compatibility features are activated if both the fishing mod and the graveyard extended mod are both installed?  But having it as a hard requirement when I want more spooky skeletons and graveyards and the like seems out of place.

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2642260
