### ISSUE TITLE
Config for Drowned spawning

### ISSUE THREAD

**Issue by AdaraChristine** [NightKosh/Gravestone-mod-Extended#178]
Im getting 2+ Drowned mobs per underwater chunk. Is that intended? Can we have a config to turn this down?

![2018-10-11_20 25 58](https://user-images.githubusercontent.com/30163566/48035452-e6a77900-e118-11e8-9ed9-92ee4828e101.png)

**Comment by NightKosh** [comment]
New options:

- SpawnWeightZombieDogs
- SpawnWeightZombieCats
- SpawnWeightSkeletonDogs
- SpawnWeightSkeletonCats
- SpawnWeightUndeadHorses
- SpawnWeightSkeletonRaiders
- SpawnWeightZombieRaiders
- SpawnWeightToxicSludge
- SpawnWeightPossessedArmor
- SpawnWeightMummy
- SpawnWeightDrowned
- SpawnWeightVampireBat
- SpawnWeightWitheredBat
- SpawnWeightBarghest
- SpawnWeightSwampThing

**PhantomDiverSpawnWeight was renamed to SpawnWeightPhantomDiver**

**Comment by AdaraChristine** [comment]
AWESOME ! THANKS!
