### ISSUE TITLE
[Suggestion] Option to Resurrect any corpse

### ISSUE THREAD

**Issue by drakray** [NightKosh/Gravestone-mod-Extended#180]
As of now, I think it's only possible to resurrect Villagers and pets, unless I'm missing something.
Could be nice to have an option to be alble to resurrect any corpse, for necromancy roleplay/resources farming.

A weapon or an Enchantment that could guarantee Corpse Drop would be nice with that, if possible.

**Comment by NightKosh** [comment]
Already planned https://github.com/NightKosh/Gravestone-mod-Extended/issues/10

I'm not sure about corpse drop by special enchantment or weapon(except player corpses). At the moment you can get corpse of "lived mobs" by killing them. I'm thinking about a special block which will be used to transform them to any other undead forms https://github.com/NightKosh/Gravestone-mod-Extended/issues/119

**Comment by drakray** [comment]
Do Witches count as "Lived Mobs"? I don't recall ever getting one

**Comment by NightKosh** [comment]
No it's not. At least you can't get its corpse at the moment.

**Comment by drakray** [comment]
Ok thanks, I'll use .addDrop from CraftTweaker to make some have a small chance to drop their corpse

**Comment by NightKosh** [comment]
@drakray I reworked graves generation so it will use loot tables since next version. Furthermore there will be a 20 % chance to get corpse of any kind of zombies, skeletons, and witches instead of villager corpse. You can read more about it here #99
