### ISSUE TITLE
New Enchantment - Soul Bound

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Extended#190]

**Comment by drakray** [comment]
Quick question: is it normal that SoulBound can be put on anything, like block and resources item(bone, flesh, etc)?

**Comment by NightKosh** [comment]
Yes it is. It was done in such way to make it able to use this enchantment on any important items.

**Comment by NightKosh** [comment]
For sure it will be incredibly stupid to use it on any ordinary block or item, such as bone or dirt. But it has a sence to apply it on something expensive, such as "frozen mirror", "shulker box"(I'm not sure what happens with its enchantments when it will be placed - can't remebmer exactly was it tested or not), or any other modded items.

**Comment by drakray** [comment]
Ah ok, I understand now, thanks :)
Placed blocks or used stuff in recipe lose enchant.
Could it be possible to have a config to disable your various enchant individually? I would like to have more control over them, specifically the SoulBound, but I think it would be a nice thing overall for pack maker :D

**Comment by NightKosh** [comment]
#196
