### ISSUE TITLE
Server doesn't start up anymore because of colliding entity with block 

### ISSUE THREAD

**Issue by ionutsoran** [NightKosh/Gravestone-mod-Extended#191]
Here is the pastebin: https://pastebin.com/9E0110iH
If you could please look into it!

**Comment by ionutsoran** [comment]
Thanks for looking into it 👍

**Comment by ionutsoran** [comment]
I also removed the entities that crashed it and the liquid with NBT explorer and now the server is able to start again. I have to mention that only after removing the cart with the chest that the server started. It didn't matter if i removed the liquid or not

**Comment by NightKosh** [comment]
It looks like I missed something in fix for #169 . I'll make a fixed version soon. Till that time you can :
1) install "advanced fishing" to prevent any problems
2) remove any "not living" entities(like minecarts or boats) which fall into toxic water. but only after crash
3) or temporary remove all toxic water

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2643145

you should wait a little - it may takes some time before new version will be approved and this download link becomes available

**Comment by ionutsoran** [comment]
Thank you very much sir! Have a great day!
