### ISSUE TITLE
1.12 update 

### ISSUE THREAD

**Issue by MadRatSRP** [NightKosh/Gravestone-mod-Extended#29]
Не хочу показаться сильно назойливым, но как скоро ожидать выход версии для 1.12.2? Это один из тех модов, без которых я не могу представить майнкрафтовскую деревню :0

**Comment by NightKosh** [comment]
Я сейчас в отпуске, далеко от дома. Вернусь только 13го. Еще неделя - две
потребуется для обновы. Если не больше

**Comment by MadRatSRP** [comment]
Спасибо за ответ. А то некоторые мододелы как пропадут на полгода-год, так как Хатико приходится ждать :) Хорошего отдыха.

**Comment by NightKosh** [comment]
Обнова для 1.11.2 готова. На выходных займусь версией для 1.12
