### ISSUE TITLE
JEI strangeness with recipes

### ISSUE THREAD

**Issue by Sunconure11** [NightKosh/Gravestone-mod-Extended#31]
![screenshot 2017-11-25 01 20 46](https://user-images.githubusercontent.com/5614902/33228009-e53b73be-d17e-11e7-83d1-c7af8231eb10.png)
![screenshot 2017-11-25 01 20 43](https://user-images.githubusercontent.com/5614902/33228010-e549eb88-d17e-11e7-9666-1d723c18f9fb.png)

**Comment by mvdhoning** [comment]
also when cheating in a stocks in creative and breaking it (in survival) gives an gallow in return.

**Comment by mvdhoning** [comment]
should i throw away configs as when breaking a stocks in a world it still returns an gallow recipes look good now.
