### ISSUE TITLE
crash generating catacombs 1.12

### ISSUE THREAD

**Issue by mvdhoning** [NightKosh/Gravestone-mod-Extended#32]
sometimes when generating catacombs minecraft freezes and show the following error in the log.
https://zerobin.net/?adbf068969c46509#kH65FUpmHoiitJ0AvHUrDr/mlNjb1XrtM+O8bAX/TIQ=

**Comment by NightKosh** [comment]
Did you generate it by command, or it was generated at world generation?

**Comment by NightKosh** [comment]
If it was generated at world generation - please give me seed of your world, and coordinates in which it was/tried to generate

**Comment by mvdhoning** [comment]
it occered at world generation:
worldgen: quark_realistic
seed: 1583336344085787454
xyz: -934 81 -1830 (somewhere around there)
i upped the spawn chance of catacombs to 75% as none would spawn otherwise, but they might have has i experienced freezes and crashes before, but did not look at log file.
at the place where catacombs are generating is also an anceint warfare 2 camp/town around. And also an Roguelike Dungeons dungeon (spawn chance 0.5).

![image](https://thuis.vanderhoning.net/images/gscatcrash1.png)

**Comment by NightKosh** [comment]
Good news - it can be easily reproduced. It looks like that the reason of this problems is huge amount of catacombs it is tried to generate.

But I need some time to fix it. I hope you have got a backup, or can revert changes.

**Comment by NightKosh** [comment]
Is it a "server" world? It is better to use console commands to generate catacombs, than change this option, especially on servers.

**Comment by mvdhoning** [comment]
its a single player test world, so nothing is lost
i will make a server world later once my modpack is more finished

**Comment by mvdhoning** [comment]
that fixed it!
reloaded the freezing world with the updated world and it does not freeze :-)
i now see a massive catacombs with even multiple buildings above ground.
so i guess i set spawn chance way to high ;-)
thanks for the quick fixing.

**Comment by NightKosh** [comment]
It is not required to reduce it - there should be only one catacombs per 1000 blocks(but it doesn't count catacombs, which were generated before every world loading). It was a bug with multiple catacombs generation near each others - it will not happens again.
