### ISSUE TITLE
Crash on Start (with Bad Mobs Mod)

### ISSUE THREAD

**Issue by Kippy232** [NightKosh/Gravestone-mod-Extended#34]
Newest version (v. 1.1.1 for 1.12.2) seems to be incompatible with the most recent version of Bad Mobs. Not sure which mod is really causing the crash here, so I'll offer the crash report to both you and Darkhax.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.3-117.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.0.4.2.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.0.0.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  CraftDevLoadingPlugin (craftdev-core-1.12.2-2.2.8.jar)
  BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 11/27/17 1:50 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.darkhax.badmobs.handler.BadMobsEventHandler.onTooltipRendered(BadMobsEventHandler.java:36)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_318_BadMobsEventHandler_onTooltipRendered_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:284)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Unknown Source)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.darkhax.badmobs.handler.BadMobsEventHandler.onTooltipRendered(BadMobsEventHandler.java:36)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_318_BadMobsEventHandler_onTooltipRendered_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:284)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Unknown Source)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 498290568 bytes (475 MB) / 1254072320 bytes (1195 MB) up to 4268163072 bytes (4070 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2552 Optifine OptiFine_1.12.2_HD_U_C6 90 mods loaded, 90 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                        | Signature                                |
	|:----- |:-------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCH   | mcp                  | 9.42                     | minecraft.jar                                 | None                                     |
	| UCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.0.2552.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.0.2552             | forge-1.12.2-14.23.0.2552.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | infinimend           | 1.0.2                    | minecraft.jar                                 | None                                     |
	| UCH   | bowinfinityfix       | rv5                      | minecraft.jar                                 | e250ba31147feb059b86cfd74ee61a8aeb88fb9b |
	| UCH   | mercurius_updater    | 1.0                      | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCH   | movillages           | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                    | None                                     |
	| UCH   | applecore            | 2.2.2                    | AppleCore-mc1.12.2-2.2.2.jar                  | None                                     |
	| UCH   | jei                  | 4.8.4.130                | jei_1.12.2-4.8.4.130.jar                      | None                                     |
	| UCH   | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
	| UCH   | astikoor             | 1.0.0                    | astikoor-1.0.0.jar                            | None                                     |
	| UCH   | attributefix         | 1.0.1                    | AttributeFix-1.12.2-1.0.1.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | autoplant            | 1.12-1.0.0               | autoplant-1.12-1.0.0.jar                      | None                                     |
	| UCH   | quark                | r1.3-117                 | Quark-r1.3-117.jar                            | None                                     |
	| UCH   | autoreglib           | 1.3-15                   | AutoRegLib-1.3-15.jar                         | None                                     |
	| UCH   | badmobs              | 1.0.24                   | BadMobs-1.12.2-1.0.24.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | basemetals           | 2.5.0-beta3              | BaseMetals-1.12-2.5.0-beta3.51.jar            | None                                     |
	| UCH   | battletowers         | 1.6.1                    | BattleTowers-1.12.2.jar                       | None                                     |
	| UCH   | baubles              | 1.5.1                    | Baubles-1.12-1.5.1.jar                        | None                                     |
	| UCH   | bibliocraft          | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar             | None                                     |
	| UCH   | biomesoplenty        | 7.0.1.2310               | BiomesOPlenty-1.12.2-7.0.1.2310-universal.jar | None                                     |
	| UCH   | birdsnests           | 2.0.0                    | BirdsNests1.12.2-2.0.0.jar                    | None                                     |
	| UCH   | bloodmoon            | 1.5.2                    | Bloodmoon-MC1.12.2-1.5.2.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCH   | bonfires             | 1.1.2                    | Bonfires-1.12-1.1.2.jar                       | None                                     |
	| UCH   | bookshelf            | 2.2.498                  | Bookshelf-1.12.2-2.2.498.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | bushcraft            | 0.0.1.0                  | Bushcraft-1.12-0.0.1.0.jar                    | None                                     |
	| UCH   | chococraft           | 0.9.1.52                 | chococraft_1.12.1-0.9.1.52.jar                | None                                     |
	| UCH   | classiccombat        | 1.0.0                    | ClassicCombat-1.12-1.0.0.jar                  | None                                     |
	| UCH   | colytra              | 1.0.4.2                  | colytra-1.12.2-1.0.4.2.jar                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCH   | comforts             | 1.0.0.2                  | comforts-1.12.2-1.0.0.2.jar                   | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCH   | craftdevcore         | 2.2.8                    | craftdev-core-1.12.2-2.2.8.jar                | 7b14aaee2dd17b12a140baecab28948fff3a263f |
	| UCH   | cttinycoal           | 1.12.2-1.0.2             | cttinycoal-1.12.2-1.0.2.jar                   | None                                     |
	| UCH   | ctwatercan           | 1.12.2-0.4.5             | ctwatercan-1.12.2-0.4.5.jar                   | None                                     |
	| UCH   | cyclopscore          | 0.10.23                  | CyclopsCore-1.12.2-0.10.23.jar                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | logicaldrops         | 0.9.4                    | EM3R50N-LogicalDrops-1.12-14.21.1.2387.jar    | None                                     |
	| UCH   | everlastingabilities | 1.3.6                    | EverlastingAbilities-1.12.2-1.3.6.jar         | None                                     |
	| UCH   | friendlyfire         | 1.5.8                    | FriendlyFire-1.12.2-1.5.8.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | giacomosfoundry      | 1.3.13                   | GiacomosFoundry-1.12.2-1.3.13.jar             | None                                     |
	| UCH   | gravestone           | 1.0.12                   | GraveStone-1.12-Graves-1.0.12.jar             | None                                     |
	| UCH   | gravestone-extended  | 1.1.1                    | GraveStone-1.12.2-Extended-1.1.1.jar          | None                                     |
	| UCH   | heartdrops           | 1.12.2-1.4.0.0           | heartdrops-1.12.2-1.4.0.0.jar                 | None                                     |
	| UCH   | hmag                 | 3.0.0                    | HMaG-mc1.12.2-3.0.0.jar                       | None                                     |
	| UCH   | waila                | 1.8.22                   | Hwyla-1.8.22-B37_1.12.jar                     | None                                     |
	| UCH   | immersivefood        | 1.12.1-0.0.2             | immersivefood-1.12.2-0.0.3.jar                | None                                     |
	| UCH   | infernalmobs         | 1.7.3                    | InfernalMobs-1.12.2.jar                       | None                                     |
	| UCH   | infinitefluids       | 1.2.0                    | infinitefluids-1.11-1.2.0.jar                 | None                                     |
	| UCH   | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironchest            | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar               | None                                     |
	| UCH   | jjraces              | 1.0.2                    | JJ Races 1.12-1.12.2-v1.0.2.jar               | None                                     |
	| UCH   | kelpie               | 1.0.3                    | Kelpie-1.12.2-1.0.3.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | leafdecay            | 1.0.0.2                  | leafdecay-1.0.0.2-mc1.12.2.jar                | None                                     |
	| UCH   | levelup2             | ${version}               | Level Up! 2-1.1.9-1.12.jar                    | None                                     |
	| UCH   | magicclover          | 1.12-0.7.5               | magicclover-1.12-0.7.5.jar                    | None                                     |
	| UCH   | mininglib            | 1.1.0                    | mininglib-1.12.1-1.1.0.jar                    | None                                     |
	| UCH   | mknutils             | 3.0.0                    | MKNUtils-mc1.12.2-3.0.0.jar                   | None                                     |
	| UCH   | netherchest          | 0.2.2                    | netherchest-0.2.2.jar                         | None                                     |
	| UCH   | nethermetals         | 1.2.0-beta1              | NetherMetals-1.12-1.2.0-beta1.15.jar          | None                                     |
	| UCH   | nightmares           | 1.0.4                    | Nightmares-1.12.2-1.0.4.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | orespawn             | 3.2.0                    | OreSpawn-1.12-3.2.0.95.jar                    | None                                     |
	| UCH   | bonecraft            | 1.12a                    | Pam's BoneCraft 1.12a.jar                     | None                                     |
	| UCH   | clayspawn            | 1.12a                    | Pam's ClaySpawn 1.12a.jar                     | None                                     |
	| UCH   | desertcraft          | 1.11a                    | Pam's DesertCraft 1.12a.jar                   | None                                     |
	| UCH   | harvestcraft         | 1.12.2a                  | Pam's HarvestCraft 1.12.2a.jar                | None                                     |
	| UCH   | simplerecipes        | 1.12a                    | Pam's Simple Recipes 1.12a.jar                | None                                     |
	| UCH   | petbat               | 1.4.7                    | PetBat-1.12.2.jar                             | None                                     |
	| UCH   | potionfingers        | r1.0-2                   | PotionFingers-r1.0-2.jar                      | None                                     |
	| UCH   | prefixation          | 1.12.2-0.0.2             | prefixation-0.0.2.jar                         | None                                     |
	| UCH   | randomthings         | 4.0.8                    | RandomThings-MC1.12.2-4.0.8.jar               | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCH   | randomtweaks         | 1.12.2-1.12.0.0          | randomtweaks-1.12.2-1.12.0.0.jar              | None                                     |
	| UCH   | xreliquary           | 1.12.2-1.3.4.724         | Reliquary-1.12.2-1.3.4.724.jar                | None                                     |
	| UCH   | roughmobs            | 1.0                      | roughMobs1.0.14-1.12.2.jar                    | None                                     |
	| UCH   | sharpbone            | 1.0                      | SharpBone-1.12.2-1.0.jar                      | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UCH   | simplegrinder        | 4.80.R1121               | SimpleGrinder-4.100.R1122.jar                 | None                                     |
	| UCH   | simplescaledmobs     | 1.1                      | simplescaledmobs-1.1.1-1.12.1.jar             | None                                     |
	| UCH   | spartanshields       | 1.3a                     | SpartanShields-1.12-1.3a.jar                  | None                                     |
	| UCH   | speedbasedfalldamage | 1.0.2                    | SpeedBasedFallDamage-1.0.2.jar                | None                                     |
	| UCH   | s                    | 1.0                      | spikey-1.0.0.jar                              | None                                     |
	| UCH   | spookycraft          | 1.0.2                    | spookycraft-1.12.2-1.0.2.jar                  | None                                     |
	| UCH   | stg                  | 1.12-1.2.1               | stg-1.12-1.2.1.jar                            | None                                     |
	| UCH   | toolbox              | 0.2                      | toolbox-0.2.jar                               | None                                     |
	| UCH   | torohealthmod        | 1.12.2-11                | torohealth-1.12.2-11.jar                      | None                                     |
	| UCH   | treechopper          | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                  | None                                     |
	| UCH   | tumbleweed           | 1.11-0.4.4               | tumbleweed-1.11-0.4.4.jar                     | None                                     |
	| UCH   | wailaharvestability  | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar         | None                                     |
	| UCH   | wearablebackpacks    | 3.1.0                    | WearableBackpacks-1.12.2-3.1.0.jar            | None                                     |
	| UCH   | witherskelefix       | 2.2.3                    | Wither Skeleton Tweaks-1.12-2.2.3.jar         | None                                     |
	| UCH   | wolfarmor            | 1.12.2-2.1.0-RELEASE     | wolfarmor-1.12.2-2.1.0.24-RELEASE.jar         | None                                     |
	| UCH   | xaerominimap         | 1.14                     | Xaeros_Minimap_1.14_Forge_1.12.jar            | None                                     |
	| UCH   | hungeroverhaul       | 1.12.2-1.3.0.jenkins131  | HungerOverhaul-1.12.2-1.3.0.jenkins131.jar    | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.3-117.jar)
  vazkii.quark.base.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  lumien.bloodmoon.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
ColytraLoadingPlugin (colytra-1.12.2-1.0.4.2.jar)
  c4.colytra.core.asm.ElytraTransformer
ComfortsCoreLoadingPlugin (comforts-1.12.2-1.0.0.2.jar)
  c4.comforts.asm.SleepTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  lumien.randomthings.asm.ClassTransformer
IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  net.crazysnailboy.mods.infinimend.asm.IMClassTransformer
CraftDevLoadingPlugin (craftdev-core-1.12.2-2.2.8.jar)
  core.upcraftlp.craftdev.asm.CraftDevClassTransformer
BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  com.github.parker8283.bif.Transformer
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2622' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.0.2552
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 2.1.0 - Build 8.15.10.2622, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3 CPU M 380 @ 2.53GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C6
	Render Distance Chunks: 3
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.0 - Build 8.15.10.2622
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Kippy232** [comment]
Also, I apologize for not using spoilers, if at all possible. I'm not quite familiar with GitHub.

**Comment by NightKosh** [comment]
It look like @darkhax fix this bug in https://github.com/Darkhax-Minecraft/BadMobs/issues/8 , so I close this issue.
