### ISSUE TITLE
1.12.2 broken recipe

### ISSUE THREAD

**Issue by MadRatSRP** [NightKosh/Gravestone-mod-Extended#35]
Рецепт рюкзака сломан: 
[18:37:21] [main/ERROR] [jei]: Found a broken recipe: GraveStone-Extended gravestone-extended:backpack
p.s. вполне возможно, что это ошибка не GravestoneExtended, а новой нестабильной версии jei или даже forestry

**Comment by NightKosh** [comment]
Не, это моя ошибка. Пытался прикрутить новое АПИ форестри, но так и не удалось. Ну и забыл закомментить рецепт.
