### ISSUE TITLE
[Suggestion] Config option to have worldgen happen per dimension?

### ISSUE THREAD

**Issue by Vyraal1** [NightKosh/Gravestone-mod-Extended#36]
Making a modpack at the moment, and I liked some of the structures that GraveStones created - however I wanted to try to see if I could have the worldgen occur in other dimensions (doesn't have to be perfectly compatible, I just want a dimensional whitelist/blacklist) as part of the mods theme is to jump from dimension to dimension.

**Comment by NightKosh** [comment]
I replaced "StructuresDimensionId" configuration option to "StructuresDimensionIds" - it should contains allowed dimensions ids, splitted by ";"
