### ISSUE TITLE
1.12.2 GravestoneExtended 1.1.1 does not work properly with latest JEI and Forestry mods

### ISSUE THREAD

**Issue by MadRatSRP** [NightKosh/Gravestone-mod-Extended#37]
Мир построен на версии 1.1.0 GravestoneExtended, он прогружается и работает нормально. Если я его убираю из модпака, мир тоже прогружается нормально. Но как только я ставлю последнюю версию GravestoneExtended, мир зависает на загрузке и не прогружается.

**Comment by NightKosh** [comment]
Логи бы. Так лишь можно долго гадать в чём дело.

**Comment by MadRatSRP** [comment]
Проверю сейчас с версией 1,2.0. И пожалуйста, добавь в Gravestone- Graves опцию в конфиге чтобы грейвстоуны без предметов и опыта не спаунились)

**Comment by NightKosh** [comment]
Как только займусь им - добавлю.

**Comment by MadRatSRP** [comment]
Проверил, сейчас всё работает. :)
p.s. Нашел еще один странный баг, на каждом грейвстоуне(или у каждого) стояли маленькие зомби, которым можно было нанести один удар, но не убить. После того, как я вышел и перезашел в мир, они пропали.
