### ISSUE TITLE
Wither arrow and wither weapon enchantments lack localizations

### ISSUE THREAD

**Issue by Sunconure11** [NightKosh/Gravestone-mod-Extended#42]
Also might be a good idea to add descriptions for the enchantments, as WAWLA picks up on that.

**Comment by NightKosh** [comment]
@Sunconure11 
1) Vampiric Touch - convert 20% of damage you deal with this sword to your health(or minimum 0.5 health points)

2) Poisoned Blade - poison your enemy. It is not compatible with "Fire aspect" and "Withered Blade". Maximal level of enchantment is 2.

3) Withered Blade - apply wither effect on your enemy. Its duration is twice lower than "Poisoned Blade" enchantment. It is not compatible with "Fire aspect" and "Poisoned Blade". Maximal level of enchantment is 2.

4) Shadow of Death - deal extra damage to peacefull mobs and any another non undead or spider mobs. It is not compatible with "Bane of Arthropods", "Smite" and "Sharpness". Maximal level of enchantment is 5.

5) Necrotic Corrosion - deal additional 10% of pure damage(that's meant it ignor all armor) per level (it can't reduce health points lower than 0.5). Maximal level of enchantment is 2.

**Comment by NightKosh** [comment]
What is wrong with localization? There are some errors? Or you'd like to ask to translate it on another language?
Also what about wither arrow? It is not mine feature.

**Comment by Sunconure11** [comment]
They have no localization.

**Comment by NightKosh** [comment]
Sorry, but I still can't understand what is wrong with it?

![](https://i.imgur.com/a24WoWe.png)

**Comment by Sunconure11** [comment]
Whoops, I confused your mod's enchantments with those of Ender Zoo's.

**Comment by Sunconure11** [comment]
https://github.com/NightKosh/Gravestone-mod-Extended/pull/44

**Comment by Sunconure11** [comment]
![lacklocalization](https://user-images.githubusercontent.com/5614902/33541207-43854b6a-d89c-11e7-96e4-f0c20d001ad3.png)

Happens with all enchants from this mod, as well as potions.

**Comment by NightKosh** [comment]
Nice. Github store localization files in uppercase.
