### ISSUE TITLE
Ukrainian localization

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Extended#49]
https://github.com/NightKosh/Gravestone-mod-Graves/issues/242#issuecomment-348816175

**Comment by coldblacksnow** [comment]
upd https://fex.net/#!394459708135

**Comment by NightKosh** [comment]
ссылка, к сожалению, не работает(

**Comment by coldblacksnow** [comment]
7 дней только работает, https://fex.net/#!291065550516

**Comment by NightKosh** [comment]
уезжал на праздники. Быть может лучше, в следующий раз скидывать в гист https://gist.github.com/ , если, конечно, вам так будет удобно?

**Comment by coldblacksnow** [comment]
окей
