### ISSUE TITLE
Fog glitch

### ISSUE THREAD

**Issue by coldblacksnow** [NightKosh/Gravestone-mod-Extended#50]
MC 1.12.2
GraveStone-1.12.2-Extended-1.2.3
GraveStone-1.12-Graves-1.0.12
1.12.2-forge1.12.2-14.23.1.2554

Был баг и раньше но стал слишком уж не комфортно выглядеть (скрины с модом и без). Если создать новый мир по началу все нормально, но через некоторое время туман на линии горизонта пропадает и остается ужасная линия.
![2017-12-04_22 23 03](https://user-images.githubusercontent.com/34198111/33577286-3575ff24-d94b-11e7-8d15-61fa949e649f.png)
![2017-12-04_22 23 47](https://user-images.githubusercontent.com/34198111/33577319-439a942a-d94b-11e7-84a4-c3b4aa6c9477.png)
![2017-12-04_22 30 12](https://user-images.githubusercontent.com/34198111/33577351-5bf15f4a-d94b-11e7-822a-04e669fd7d9d.png)
![2017-12-04_22 31 05](https://user-images.githubusercontent.com/34198111/33577360-676c09ce-d94b-11e7-982d-9c5070bca45b.png)

**Comment by NightKosh** [comment]
По ссылке ничего не находит

**Comment by coldblacksnow** [comment]
да я уже сюда кинул скрины

**Comment by NightKosh** [comment]
Спасибо за скрины. Сразу скажу, что фиксить это, скорее всего, буду долго. Но туман, если мешает, можно отключить в настройках.
