### ISSUE TITLE
Mod Compat Crash, Evilcraft, MCA

### ISSUE THREAD

**Issue by drakray** [NightKosh/Gravestone-mod-Extended#51]
java.lang.NullPointerException: Ticking entity
[...]
	at nightkosh.gravestone_extended.item.corpse.VillagerCorpseHelper.setNbt(VillagerCorpseHelper.java:91)
[...]
	at mca.entity.EntityVillagerMCA.func_70645_a(EntityVillagerMCA.java:262)
[...]
	at org.cyclops.evilcraft.entity.monster.Werewolf.func_70636_d(Werewolf.java:151)
[...]

https://pastebin.com/1V3T89tR
Minecraft 1.12.2
Forge 2558
GraveStone-1.12-Graves-1.0.12
GraveStone-1.12.2-Extended-1.2.3
MCA 5.3.1
Evilcraft 0.10.40

Crashed when going to sleep, one random time (I slept before with no problem)

**Comment by NightKosh** [comment]
It crashed at "Minecraft Comes Alive"(Am I right?) villager death. It's tried to create its corpse and fails. Thank you for report. I'll try to fix it in the nearest time.

**Comment by drakray** [comment]
Indeed MCa is Minecraft Comes Alive lol
Could it have something to do with the Trade List? Because I saw some villager with crazy long list of trade, like ALL saplings from Harvestcraft (don't remember which mod add those, as it's not HC I think)

**Comment by NightKosh** [comment]
Size of the trading list should not affect on it, but maybe you are right - logs you are posted tells that it's crashed at trade list reading.

**Comment by drakray** [comment]
Could it be an "Invalid Entry" type of thing?

**Comment by NightKosh** [comment]
@drakray Unfortunately I failed to reproduce this issue. At the same time I inspected the logs and code, and expect that reasons of this issue can be combination of "empty items" changes of the Minecraft 1.11 and "broken recipes list" of died villager. Anyway I added additional checks, and exception handlers so even if this problem occurs again game will not crashed.

**Comment by drakray** [comment]
Good, if I come across another one of these I'll keep you posted, hoping not lol

**Comment by drakray** [comment]
I got a new [Hanging Crash](https://pastebin.com/WEVXA5Ly), while I was mining near(under) a village.
Seems like a Karate Zombie from Better With Addons killed a Minecraft Comes Alive villager, and Gravestone Extended tried to make a corpse but failed on the Recipe List again?

**Comment by NightKosh** [comment]
Not exactly, it failed when tried to store it. 
I added additional exceptions handlers, and new configuration option "CreateCorpsesForModdedNotVanillaVillagers". It set to false by default and disable corpse generation for any specific modded villagers(like in Minecraft Comes Alive) to prevent such unpredictable errors

**Comment by drakray** [comment]
good, will keep you updated here if something else happens with this kind of trouble(I temp disabled GenerateVillagersGraves for now, should patch it?)

**Comment by NightKosh** [comment]
Yes it should.
I can provide you fixed version, but it's not completed - one of new liquid block is invisible. Is acceptable or you'll wait a little.

**Comment by drakray** [comment]
I'll wait thanks, no rush
