### ISSUE TITLE
Crashing with new version 1.2.5

### ISSUE THREAD

**Issue by Gamerbolts** [NightKosh/Gravestone-mod-Extended#55]
Hi there, so I downloaded the new version 1.2.5 and tried loading my modpack and crashed. Here is the error log. https://pastebin.com/UVPNH5Mf

Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here, or at least past it directly to the issue and embrace by "```".
 * If it is possible provide your logs.
 * Please provide your Minecraft version, Forge version and "Graves" and "Extended mods version.
 * Any additional information how to reproduce your problem and screenshots will be helpful.

**Comment by coldblacksnow** [comment]
same crash

GraveStone-1.12-Graves-1.0.12
GraveStone-1.12.2-Extended-1.2.5
mc 1.12.2
1.12.2-forge1.12.2-14.23.1.2555

https://gist.github.com/sonofthesnow/dc5142296315eff15ad724cd7c5ad258

ps проверял без остальных модов, только GraveStone-1.12-Graves-1.0.12
GraveStone-1.12.2-Extended-1.2.5, все аналогично

**Comment by drakray** [comment]
[One more](https://pastebin.com/wkapBXr5) for luck

Mc 1.12.2
Forge 2558
GSG 1.0.12
GSE 1.2.5
\+ a bunch more

**Comment by trogarus** [comment]
And another to be sure you have all the data you need

[crash-2017-12-10_14.50.38-client.txt](https://github.com/NightKosh/Gravestone-mod-Extended/files/1546017/crash-2017-12-10_14.50.38-client.txt)

MC 1-12-2
Forge 2555
GraveStone-1.12-Graves-1.0.12
GraveStone-1.12.2-Extended-1.2.5

**Comment by NightKosh** [comment]
Fixed https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2508439

**Comment by Gamerbolts** [comment]
Awesome! It worked. Thank you very much
