### ISSUE TITLE
Bone Shield

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Extended#57]
![ftdcaxjz3xs](https://user-images.githubusercontent.com/4181327/33876843-b69ecf1c-df37-11e7-8fd9-1cbaa09c5cc0.jpg)

**Comment by coldblacksnow** [comment]
круто, как на счет костяной брони? (только она должна быть не лучше алмазной где-то как железная но с какими то фичами, типа как у золотой шанс получить больше зачарований или резист от снарядов, ну или возможность красить как кожаную)

**Comment by NightKosh** [comment]
В планах, как и остальные инструменты. Но, в отличии от щита, в несколько тиров, как с мечами - просто костяная и далее комбинации из костяных и железных/золотых/алмазных - по стоимости выходит дороже ванильных аналогов(особенно учитывая, что столько костей тупо "рашем", как с алмазами, добыть не получится, не говоря уже про черепа + в дальнейшем крафт "комбинированных" предметов будет перенесён на алтарь с дополнительными требованиями), по "стандартным" характеристикам - тоже самое, только с возможностью доп энчанта. Но вот бронёй, я скорее всего, займусь в последнюю очередь(разве что просто костяную сделаю раньше) - достаточно много работы с учётом того, что для "комбинированных" вариантов в планах сделать более сложные модельки, чем используются в обычной броне.

**Comment by NightKosh** [comment]
Кстати, может есть идеи энчантов для щита, брони и инструментов(топор/кирка/лопата и, возможно и для удочки и мотыги)?

Для щита единственное что сейчас есть в мыслях - при блокировке с некоторой вероятностью возвращать весь урон обратно. Но тут я не очень уверен - очень схоже это с энчантом на шипы для брони.

С энчантами для кирки, топора и лопаты всё как-то тяжко - логично было бы увеличить скорость ломания блоков, но для этого уже есть эффективность. Можно для кирки и лопаты расширить область действия до 3х3 блоков, как было в таумкрафте, но блин даже не смотря на то, что он так и не обновлён(и возможно и не будет), там такое уже есть(для лопаты), да и есть ощущение что возможно это слишком имбово. Для топора в мыслях энчант на срубание всего дерева разом, либо опять же, как в таумкрафте срубание дерева "с конца", но опять же не уверен насколько это нормально. С мотыгой вообще хз, да и сомневаюсь, нужна ли она.
Вот с удочкой проблем нет - у неё будет дефолтная фича - ей можно будет рыбачить в "токсичной воде"(название примерное)  + возможно энчант, чтоб можно было ей рыбачить в лаве.

С бронёй всё чуть проще - для шлема на выбор пониженный урон от яда/иссушения, для обуви - нормальное передвижение в паутине(не уверен, можно ли это реализовать) и, возможно, ходьба по лаве(по аналогии с энчантом на заморозку воды под ногами). Но вот что делать с нагрудником и штанами - пока что идей нету.

Что касаемо лука - опять же 2 стула, с одной стороны можно было бы зачарить на иссушение/отравление как с мечами, но, с другой стороны в майне уже есть "отравленные стрелы".
Можно, как вариант, ещё запилить ему чарку на создание блока паутины в месте падения стрелы, но это выглядит как-то слабо применимым(разве что на серваках пвпшиться)

**Comment by coldblacksnow** [comment]
хм, хорошо, выскажу мысли, это будет только моя точка зрения и не будет означать что так должно быть.

главное, мне кажется, так как твой мод базируется на смерти\зомби\трупах нужно не отходить от тематики и все свойства\зачарования выполнять в этом же направлении.

1) БРОНЯ, просто зачарования выглядят не особо привлекательно так как (в моем случае) другие моды тоже добавляют свои зачаронавия и когда их собирается достаточное количество получить\найти\выбить нужное стает еще тем испытанием, как вариант если ты все же захочешь добавить зачарование, круто было бы сделать отдельную систему\способ зачарования твоих вещей(из твоего мода), что-то типа особого стола зачарования(либо зачарователя который будет продавать эти книги или еще что-то в таком духе) чтобы они не пересекались с ванильными, да и  уже существующие перенести сюда же, лучше всего отказаться от книг и использовать какие то предметы(в крайнем случае лвл) типа особых черепов, медалек, душ.. но в этом случае зачарования должны быть действительно интересными. в качестве пожелания\совета твои зачарования должны применяться только к твоим вещам(ванильные также должны применяться к твоим), это предаст им больше значимости.
мне больше нравится другой подход, когда полный комплект будет давать какие то бонусы и тут все стает более интереснее(скажу сразу что в практической реализации я не разбираюсь я этим никогда не занимался, буду говорить только в теоретической, тобиш то что я буду считать возможным реализовать, а решать уже тебе можно это сделать и стоит ли оно того)
на пример к золотому сету было бы круто добавить ауру "сеяния небес"(N блоков расстояния) которая будет поджигать нежить по аналогу дневного света, тобиш ночью(или в пещерах) она будет поджигать врагов, пока они находятся в радиусе, ну и как визуальный эффект добавить небольшого свечения всему сету\отдельным частям\глазам черепов наплечников итд.
придумал все это экспромтом и что бы даром "не портить бумагу" если тебе интересно, могу подумать над остальными сетами в таком роде.

2)ЛУК, дублировать уже существующий лук не особо круто, думаю тебе нужно сделать арбалет, не особо оригинально, но зато можно реализовать хорошую модельку без анимации натягивания, который будет стрелять костяными болтами(перо + кость + кремень\железо\золото\алмаз) фишка будет в том что на болты не будут так сильно влиять гравитация, также типы стрел могут иметь какие то свои свойства( и не нужно придумывать особых зачарований) можно придумать еще какую то альтернативу если тебе интересно напиши и над этим подумаю

3)ЩИТ, если бы у тебя были разные щиты, то моно было бы добавить какое то дополнительное свойство сету, но если будет один то все так же не думаю что нужны какие то зачарования, нужно какое то особое свойство, отражать стрелы\снаряды назад в стреляющего(что то похожее есть в посохе в моде "roots 2")

4)МОТЫГА, есть предложение, не знаю стоит оно того, но я вижу это так, добавить в нее слот, по нажатию шрифт + пкм открывается окно в котором будет возможность вставить в этот слот костяной порошок, в результате с мотыгой в руках при нажатию пкм на растение она будет его удобрять, возможно сделать умножение пороха, используется из слота один но дает N количество применений

по поводу остального не успеваю написать, нужно на тренировку, но ты скажи если тебя заинтересовало, то буду рад что-то придумать

**Comment by coldblacksnow** [comment]
п.с. много редактировал и переписывал из-за экспромта потому может быть не понятно)

**Comment by NightKosh** [comment]
1) В дальнейшем я планирую глобальную переделку алтаря(а возможно и разделение на несколько различных типов) и вынести туда не только воскрешение мобов а так же большую часть специфичного крафта, зачарование(но не за экспу а через жертвоприношения мобов + спец ингредиенты, а так же вынести туда все мои энчанты - чтоб стандартным способом их получить было нельзя), дизэнчант предметов и прочие фичи.
2) по поводу кастомных чар - сейчас те, что я добавил для мечей доступны только для костяных мечей и не могут быть применены к любым другим - то же самое я планирую сделать и с энчантами для брони/кирки и прочих вещей
3) идея использовать черепа вместо книг для хранения чар выглядит очень круто!
4) Про сеты - спорная тема. Сама по себе идея хороша, но в майне уж слишком мало бронек и в рамках одного мода оно в полной мере себя, к сожалению, не проявит - как такового выбора толком нет. Тем не менее для костяных предметов и брони(помимо энчантов), как встроенную фичу, я планировал запилить не восприимчивость к "ржавчине" - дебаф который будет добавлен в одной из следующих обнов и дамажить броню и предметы в руках. Его навешивать будут специальные "токсичные/кислотные слизнюки", редко спаунящиеся повсеместно в тёмных местах под землёй(а так же они после смерти будут разливать "токсичную воду", которая будет накидывать тот же дебаф при прикосновении, и использоваться в различных специфичных крафтах(например для конвертации обычных трупов в трупы скелетов))
5) С арбалетом идея не плоха. Возможно так и сделаю - пока что не уверен. Вообще у меня были идеи об арбалете, но немного в другом контексте - после реализации давно запланированной фичи с нормальной системой крафта надгробий/мемориалов заменить торги у гробовщика на более дешёвые варианты надгробий, а для продажи черепов запилить другого жителя(не совсем, т.к. он будет ещё и от мобов отбиваться) - охотника на ведьм(как раз к нему перед домом хорошо подойдут висильница/колодки/костёр). Соответственно для него отдельный сет кожаной брони(выдержанный в соответственной стилистики) - полностью эквивалентной обычной кожаной, но со встроенной фичей, избавляющей от всех негативных дебафов - как зелье очищения. И ему же я и думал запилить арбалет(с дополнительным дамагом против нежити).
6) Насчёт мотыги - тоже задумывался о подобном. В принципе даже и слот для этого не нужен - всё же она костяная, и "костная мука" и так с неё сыпаться может - а в замен потеря прочности. Но тут опять же - точно такая же фича была в таумкрафте. Да и, что меня больше всего беспокоит в этой идеи - как ты сам сказал "мод базируется на смерти\зомби\трупах" и стоит все фичи выдерживать в подобной тематике - а тут считай что полная противоположность. А так да - была бы супер полезная фича(особенно то с новыми чарами на починку). Хотя можно это реализовать как специальный энчант - тогда оно, возможно, и не так сильно будет идти в разрез тематикой мода.

**Comment by coldblacksnow** [comment]
в таумкрафт я никогда не играл, потому не знаю что там было что не было, есть пару идей, думаю напишу тебе в приватное сообщение чтобы не засорять сторонние топики
