### ISSUE TITLE
some fix for cemetery

### ISSUE THREAD

**Issue by coldblacksnow** [NightKosh/Gravestone-mod-Extended#61]
было бы не плохо добавить "каркас" из воздуха для кладбищ о дома могильника при генерации, что бы все выглядело более естественно, потому что лично у меня больше чем в 50% случаев кладбище под землей как минимум на половину.
![2017-12-10_22 29 07](https://user-images.githubusercontent.com/34198111/33911541-66fd25d0-df9b-11e7-9504-ac811da19c4e.png)
![2017-12-10_22 32 25](https://user-images.githubusercontent.com/34198111/33911555-6f26d26a-df9b-11e7-8b91-65847f152704.png)

**Comment by NightKosh** [comment]
Странно, но это уже было реализовано. Скорее всего это стандартная ванильная проблема с генерацией мира, когда здания частично, или даже полностью оказываются под землёй в холмах/горах.
Хотя может быть и я накосячил при мердже кладбища с домом гробовщика. Если не трудно - был бы рад сиду этого мира и координатам деревни, для тестирования.

**Comment by coldblacksnow** [comment]
не, сида и мира нету, да и толку не было бы потому что я играю с MoVillages-1.5.4 что увеличивает количество деревень и добавляет их во все биомы.
вот создал новый мир(без посторонних модов) и попытался найти что-то, но в ванильной генерации сложновато найти деревню да и не всегда кладбище есть, в примере только над забором чуток
сид -4219173730424541908
![2017-12-13_15 51 05](https://user-images.githubusercontent.com/34198111/33943288-5ffb5078-e021-11e7-8ccd-8c46ca0baea1.png)

**Comment by NightKosh** [comment]
ок, спасибо, буду тестить да фиксить

**Comment by NightKosh** [comment]
Всё же это был мой косяк.
