### ISSUE TITLE
New mob - Toxic Sludge

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Extended#64]
Add new slime-like mob - "Toxic Sludge".
It should be rarely spawned everywhere underground in dark places.
Every time it attack you your armor / shield(in case you block it) should recive additional damage - the same for melee weapon when you attack it. It should not has any effect if this is "bone item" or if you under "bone skin potion". 
Blocks convertations at interraction:
- Grass to dirt
- Farmland to dirt
- Grass path to dirt
- Podzol to dirt
- Mycelium to dirt
- Stone to cobblestone
- Stone bricks to damaged stone bricks

Big and medium species should create a block of "toxic water" at death.
Small species should drop "toxic slime" at death.

"Toxic water" should apply "Rust potion" and deal small damage to any creatures(except toxic sludges and undead mobs) without full set of bone armor or applyed "bone skin potion". Also it should change nearest blocks like toxic sludge do and extremelly slowly convert any nearest blocks of water to "toxic water" (it should be configurable)

"Rust potion" - any creature under this potion should recive additional damage to its armor and items in hands if this is not bone items or if this creature not under "Bone skin potion". It should be crafted of "Toxic slime" and awkward potion.

"Bone skin potion" should protect any creature from any addition items damage by "Toxic Sludge", "Toxic water" or "Rust potion". It should be crafted of "mundane potion" and "bone".

TODO:
- [x] Toxic Sludge
- [x] Toxic Slime(item)
- [x] Rust Potion
- [x] Bone Skin Potion

**Comment by Tyranuss** [comment]
I know it is closed, but I need to re-open it. Unfortunately you have implemented this, and it causes an issue with my mob farm. 
Every so often (it creates,about every two minutes,  a new toxic water source block) which in turn spreads and blocks the spawning area. 

Is there a way to: a) disable it b) maybe collect it at range  so the farm still functions and the source block is still collected? 

Any help would be much appreciated.

**Comment by NightKosh** [comment]
I'll add proper option for it. At the moment the only way to fix it on your side - light the area where they spawn. But I guess it is not an option for you, at least in case your farm is underground(those slimes can be spawned only in darkness at height 30 or lower)

**Comment by NightKosh** [comment]
@Tyranuss in next version toxic sludge will be able to spawn only on the stone, cobblestone, dirt and gravel blocks. So just replace ground in your farm by any another blocks to prevent spawn of them.
Sorry for late fix.
