### ISSUE TITLE
Feature Request - configurable grave content

### ISSUE THREAD

**Issue by Divineaspect** [NightKosh/Gravestone-mod-Extended#69]
The ability to config or use loottables for grave content.

**Comment by coldblacksnow** [comment]
действительно нужна возможность настраивать шанс дропа, сильно много алмазной брони

**Comment by NightKosh** [comment]
@sonofthesnow слишком много в могилах на кладбищах в деревнях или вообще в любых? просто с кладбищами есть баг - они генерятся по несколько раз, из-за чего контента в них раза в 3 - 4 больше нужного(бага пофикшена, но версия ещё не выложена). Если речь про "вообще", то будет ли приемлемым вариантом "фикса" навесить на них энчант - "проклятие утраты" и ещё чего-нибудь из планируемых мной "энчантов-проклятий", дабы понизить их пользу?

**Comment by coldblacksnow** [comment]
хм, ну думаю для начала я бы взглянул на твой фикс, а потом уже что-то предложил
на данный момент очень много ништяков в могилах на кладбище в деревне(и кладбище возле могильщика), даже пожалел что включил их спавн, к одиночным могилам особо претензий нету их не так легко найти

**Comment by NightKosh** [comment]
will be done in #99
