### ISSUE TITLE
Toxic Water

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Extended#73]
Were part of   #64
- [x] Toxic Water renderring
- [x] Toxic Water behaviour
- [x] Bucket of Toxic Water
- [x] Replace Lava in catacombs by Toxic Water
~~- [ ] Drip particle~~

**Comment by NightKosh** [comment]
Hello @Sunconure11 . As I know you are working on a Bewitchment mod, aren't you? It looks like this mod adds own fluids, so maybe you can help me with my problem, or just give me any advice. Unfortunately my fluid used water texture instead its own, and I can't understand why it happens.
I described this problem in details here http://www.minecraftforge.net/forum/topic/62138-1122-custom-fluid-is-invisible/

**Comment by Sunconure11** [comment]
Just look through the source code of my mod, as it's open source, you are free to take from it, but here's the blockstate for fluids, just in case:

https://github.com/Um-Mitternacht/Bewitchment/blob/master/src/main/resources/assets/bewitchment/blockstates/fluid.json

As well as the code where fluids are declared:

https://github.com/Um-Mitternacht/Bewitchment/blob/27b97ddc6a62b1041579761440e60720305b4844/src/main/java/com/bewitchment/common/block/natural/fluid/Fluids.java

**Comment by NightKosh** [comment]
Thank you a lot! Finally I fix it. 
To be honest, I'm still not completely understand what was wrong with it - at the moment all code mostly the same.. 
But it doesn't matter any more)

**Comment by NightKosh** [comment]
new config option:
- "SpreadToxicWater"
- "RemoveToxicWater"
