### ISSUE TITLE
[1.12.2] Server Crash

### ISSUE THREAD

**Issue by Draskh** [NightKosh/Gravestone-mod-Extended#83]
I got crash with the newest version of Gravestone Extended.
[crash-2017-12-27_20.05.06-server.txt](https://github.com/NightKosh/Gravestone-mod-Extended/files/1589696/crash-2017-12-27_20.05.06-server.txt)

**Comment by P3rf3ctXZer0** [comment]
I have the exact same crash 
[crash-2017-12-27_14.41.48-server.txt](https://github.com/NightKosh/Gravestone-mod-Extended/files/1589999/crash-2017-12-27_14.41.48-server.txt)

**Comment by Sunconure11** [comment]
I think something in the mod needs to be client-ended. Pinging @NightKosh

**Comment by drakray** [comment]
Yeah, got that too, Linux Server
https://pastebin.com/Gdfe0h2t
Windows Client load fine though

Minecraft 1.12.2
Forge 2582
Gravestone Extended 1.3.0a1
+BunchO'other

**Comment by NightKosh** [comment]
Hello. Sorry for waiting. I'm far away from home at the moment. I'll return to home at January 5th.

**Comment by NightKosh** [comment]
Hello. I fixed this error. Right now I'm rather tired after a full day in the way back to home, so I'll make all additional tests at tomorrow morning, and publish fixed version.

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2516921
